### ISSUE TITLE
Peer review feedback

### ISSUE THREAD

**Issue by sreen020** [BVictorB/frontend-data#1]
- Project nog niet online op github pages
- Concept is prima te begrijpen als je de datavis al hebt gezien maar voor andere denk ik nog erg onduidelijk. Een screenshot zou hierbij kunnen helpen.
- Je hebt wel de hele curren course gelinked maar niet een specefiek example
- Goed verschil laten zien tussen dataobject toen en nu
- Laat weten wat je geleerd hebt deze periode

**Comment by BVictorB** [comment]
GH pages -> done
Curran course -> done

Will do the rest asap.
Thanks for the feedback!
